### ISSUE TITLE
markov test crashes.

### ISSUE THREAD

**Issue by dj-on-github** [usnistgov/SP800-90B_EntropyAssessment#1]
I have a 33 Mbyte files of 70% entropic bit serial binary data.
]# ls -l raw.bin
-rw-r--r--. 1 user user 33554434 Nov  6 17:21 raw.bin

Running through a C markov test implementation we get this:
]# entropyTest -t markov -i 1 -o 1 -s 9 -g 10 raw.bin
Warning: steps = 9 (10 samples)
Warning: groupLength = 10
Filename: raw.bin
Test name: markov
Number of samples: 16777216
Number of events: 0
Mean score: 0.000000
Adjusted mean score: 0.000000
Standard deviation: 0.000000
Entropy type: min-entropy
Entropy estimate: 7.084931

This same file passed through the python markov implementation crashes:
]# python noniid_main.py raw.bin 1
        collision test not run:
        mu_bar = 13.1448, max valid value for this test and model = 2.5
- Collision test *not valid* for this data set.
        partial collection test not run:
        mu_bar = 1.99181, max valid value for this test and model = 1.5
- Partial collection test *not valid* for this data set.
Traceback (most recent call last):
  File "noniid_main.py", line 93, in <module>
    pmax, minH = markov_test(dataset, n, 0.95)
  File "/root/sw/est/markov.py", line 28, in markov_test
    count[dataset[-1]] -= 1
IndexError: list index out of range

The file has nothing funky in it..
]# od -x raw.bin | head
0000000 46a9 a935 3e1a 9aaa e0a9 28ba 5b28 c9aa
0000020 ba15 a205 da35 6a2b 5522 5306 5ab4 0139
0000040 559d c51a 419a 3d93 7ba1 4d08 532a 9a13
0000060 65a5 c29e aba2 3d85 5a36 aaa4 a539 5d99
0000100 94a4 86ba 629e 9d14 e286 ac9d 9a09 5582
0000120 452d 9297 74b4 3aa3 a9aa 5b88 3123 293b
0000140 51a4 55b6 6519 6d39 9730 aa96 1209 8a1f
0000160 aa9c baaa 41a9 6696 a530 aab8 ee85 500a
0000200 ca95 a90a 558c 53a2 6ba2 5da4 3227 53a6
0000220 2db6 95a5 2529 b2a2 5494 aeab 5d94 bca5

**Comment by kerrymckay** [comment]
I think this is happening because the parser converts the binary file by bytes. In the comments for to_dataset in util90b.py, it states: "Note that 1 bit per symbol assumes that 1 bit per byte is used, the data is not packed (i.e., 8 1-bit output samples are not packed into 1 byte)". When multiple 1-bit symbols are packed into a byte, this error occurs. dataset[-1] is the value of the last byte in the data, and if it is not 0 or 1 it is not an index in count, which I'm guessing is the case in raw.bin.

If you try to run the test on raw.bin with 8 bits per symbol, does it work or do you still get this error?
