### ISSUE TITLE
why do the conversion2() before numRunsMedian test?

### ISSUE THREAD

**Issue by hlsun111** [usnistgov/SP800-90B_EntropyAssessment#107]
@joshuaehill hi, I'm confused that why we should do the conversion2 function before numRunsMedian test and lenRunsMedian test? Because the SP800-90B said “No additional conversion steps are required.” in section 5.1.5 and 5.1.6. I am looking forward to your reply.Thank you!

**Comment by joshuaehill** [comment]
That looks like a bug. Good catch!

For those following along at home:
5.1.5 is implemented in num_directional_runs() (when applied to alt_sequence_2) and 5.1.6 is implemented in len_directional_runs() (when applied to alt_sequence_2). This occurs in consecutive_runs_tests().

This appears to date from the original release, but the fix is easy enough. While I'm looking at binary permtest data, it would appear that the collision tests are also returning incorrect results. I'll look into that, as well.

**Comment by joshuaehill** [comment]
OK, I've created pull request #111 that resolves this issue (along with several others). Let me know if you have any questions or comments.
