### ISSUE TITLE
Binary symbols as half of input binary bit stream length

### ISSUE THREAD

**Issue by sachin-taneja** [usnistgov/SP800-90B_EntropyAssessment#123]
Question : 

In Section 3.1.1, SP 800-90B document suggest that 1 million sample values are required for the sequential dataset testing. 

Performing ea_iid on truerand_1bit.bin displays message that "Symbol alphabet consists of 2 unique symbols" , This requires 2 million binary bits for the test (which might be difficult to collect in some cases). 

It seems that code is combining the 2 binary bits to make symbol but 1 bit binary can be treated as a symbol. 

I am working towards more understanding of code meanwhile, It will be helpful if details/insights about this can be shared.

**Comment by joshuaehill** [comment]
I think that you might be confused about the difference between "samples" and "symbols". In SP800-90B testing, you need 1 million data samples, total, irrespective of how many symbols are present.

So, for truerand_1bit.bin, there are two distinct symbols ("1"s and "0"s), but 1-million different samples.

**Comment by sachin-taneja** [comment]
Thanks Joshua, I was indeed confused between the usage of samples and symbols as i was working with binary 1 bit output.

I agree with this statement " In SP800-90B testing, you need 1 million data samples, total, irrespective of how many symbols are present. "

Number of distinct symbols is equal to 2^bit (=1) . 1 bit output leading to two symbols (1 ,  0). Please correct me if my understanding is not correct.

1.  truerand_1bit.bin contains two million 1 bit different samples as example in bin folder. 
2.  I converted this file and reduced total number of samples to first 1 million (as per 800-90B) and converted back to .bin file for ea_iid test. 
3.  Code output says that data contains less than 1 million samples as per below  

Report output (First few lines) : 
Opening file: 'truerand_1bit_one_col_1Mb.bin'
**Number of Binary Symbols: 500000**
*** Warning: data contains less than 1000000 samples ***

It will be helpful if insight about this can be shared.

**Comment by joshuaehill** [comment]
The number of distinct symbols is the number of different symbols that appear in the input stream; for a "bit"-wide data set, this count is bounded by 2^bit, it isn't necessarily equal to that. The symbol width is the just the number of bits used to represent each symbol. So (for example) the binary string "0x80 0x01" is two distinct symbols, but an 8-bit width.

This tool requires that all symbols be presented in 1 symbol-per-byte, irrespective of the bit width of the data, so you don't have to do anything to the provided binary files because they are already in this format.

truerand_1bit.bin contains 1 million bytes. It contains 1 million 1-bit symbols (the low order bit of each byte).

You may want to play with the pull request that I recently proposed (pull request #118); this version of the code does not require you to specify an explicit bit width, but rather it defaults to the smallest bit width that can contain all of the provided samples.

**Comment by sachin-taneja** [comment]
Thanks Joshua for detailed explanation for the truerand_1bit.bin file organization. I will also try the suggested pull request code.

Thanks once again.

**Comment by joshuaehill** [comment]
@celic I think that this issue can be closed.
