### ISSUE TITLE
Print version number in output

### ISSUE THREAD

**Issue by mslpensec** [usnistgov/SP800-90B_EntropyAssessment#124]
Because the labs are required to report what version of the official 90B tool is used, it would be helpful if the program printed a version number or some other identifying information as the first line of any test. This would eliminate book keeping requirements and ensure there is no confusion over what version is used.

It would also be helpful to have the version number somewhere in the readme so that it is easily accessible.

**Comment by celic** [comment]
I'll look into this. As there are several binaries to use, we'd like to keep them all in sync without needing to update many locations for a version number every time an update is made. Obviously there are solutions to this.

**Comment by joshuaehill** [comment]
One option (which happens to be what we do) in the short term is to run the analysis binary from a script, and include the version of the binary in use in the script's output.

It would surely be nice to get some "release version" from the binary, but it would require manually updating this value as the development of this tool continues (including between formal releases).

**Comment by celic** [comment]
It would be up to the lab at that point to write and maintain the script. But in the event that this gets lost somehow, a `--version` or something might help.

**Comment by mmccarl** [comment]
it is possible to make versioning a bit more automatic by using the 'attributes' feature of git:

in the project directory, add the following lines to .git/config:
    [filter "versioning"]
     smudge = sed -e s/\\\\\\$Version.*\\\\\\$/\\\\\\$Version:\\ `git describe --tags`\\\\\\$/g
     clean = cat

then create the file '.gitattributes' in the project directory and add this line:
  *.cpp filter=versioning

(note: you could enter '*main.cpp filter=versioning' instead to limit the files that are filtered)

then in each of the 'main.cpp' files insert the following somewhere in the main() function (I put it right before the switch statement). Something similar would be needed for the JSON output too:
  printf ("$Version$\n");

when you check in the changes to the main.cpp files, nothing will get modified, but when you check them out the 'smudge' filter will change the $Version$ to "$Version: v1.1.3-2-g432ef59$".  To force this update to your working directory, after you check in the main.cpp files, delete them and then do a checkout.  

the first time you check out the main.cpp files, they will immediately show as modified when you do a 'git status' command.  check them back in and the version information (with tag) will now be in the repository so that anyone who has cloned the repository will now get the correct tag on the version. (folks who cloned the repository don't need to implement these changes to .gitattributes or .git/config).

for new versions, tag the repository, delete the main.cpp files then check them out again.  the smudge filter should update the version and the main.cpp files can be checked in again.

one other note: it is possible to add the filters via the 'git config' command with the --local option, but counting backslashes is a pain (each '\\' above would need to become '\') and it is easier to just cut/paste the lines given here.

btw, i think the program should always output the version info without any special options necessary to do so.  a --version option could be added if you only want the version info and nothing else.

**Comment by celic** [comment]
`--version` is available on all executables.
