### ISSUE TITLE
Find some results differ from standard samples

### ISSUE THREAD

**Issue by QunixZ** [usnistgov/SP800-90B_EntropyAssessment#171]
Recently I'm working on the IID test for a noise entropy source. This tool worked well in all the tests as I successfully ran ./ea-iid. But there I got a **different result** compared to SP800-90B pdf samples:

- In Section 5.1.7 & Section 5.1.8, two Collision Tests are introduced,  with a sample input sequence `S =  (2, 1, 1, 2, 0, 1, 0, 1, 1, 2)`, and this sequence should got a result like `C = [3, 4, 2]` after a Collision procedure.
- But the tool's calculation gives a different result as `C = [2, 3, 1]`, and of course result in a different statistic average/maximum number && c0* in later Permutation Test.

So I found there https://github.com/usnistgov/SP800-90B_EntropyAssessment/blob/7afbdac8baee67bf863546fa827777b7c50c3137/cpp/iid/permutation_tests.h#L201-L215
Notice that the `ret.push_back(j); ` records the Collision result `C`, while `i, j` are set to 0 in the beginning at here https://github.com/usnistgov/SP800-90B_EntropyAssessment/blob/7afbdac8baee67bf863546fa827777b7c50c3137/cpp/iid/permutation_tests.h#L193-L194
So when recording the Collision info, the `j` always get 1 less than current Collision's real length.

I wonder if this a trick in coding or just a small oversight? Cause such results will be shown in the final report of my noise entropy source, it's quite important to confirm that all the statistic data are strictly calculated by a certain procedure defined in SP800-90B.

**Comment by joshuaehill** [comment]
This is a small oversight, and should be fixed by making the recording line `ret.push_back(j+1)`. The meaning of `j` in this code is different than in 90B, but (as you already noted) you can map it to the "90B `j`" by just adding `1` to the value.

I wrote an independent (indeed, developed prior to the NIST tool's release) implementation of this test - now included in [Theseus](https://github.com/KeyPair-Consulting/Theseus) - and I had compared the outputs of the two tools, but I sadly had an equivalent bug in my code, so I never noticed the problem.

That being said, this bug shouldn't have any impact on the permutation testing results for either the Maximum Collision Test Statistic or Average Collision Test Statistic results (as in both cases, the bug effectively adds `1` to the resulting statistics, which is an order-preserving bijection). The permutation test results are invariant under any order-preserving bijection, so this doesn't change the end results at all.
