### ISSUE TITLE
Markov Estimate Significantly lowers assessed entropy

### ISSUE THREAD

**Issue by mslpensec** [usnistgov/SP800-90B_EntropyAssessment#34]
In the current build, the entropy output of each test is compared and the minimum value is passed to the output. This is a valid comparison for every test except for the Markov test. Because the Markov test reduces the dataset to six bits per symbol, the maximum possible assessed entropy is 6 bits. This means that a test can actually perform very well under all test statistics, but still have a very low assessed entropy. This is an example of the output of the tool on the true random data provided with the entropy assessment (truerand_8bit.bin):

_Running entropic statistic  estimates:_
_- Most Common Value Estimate: p(max) = 0.00428909, min-entropy = 7.86511_
_- Collision Estimate: p(max) = 0.0127256, min-entropy = 6.29613_
**_- Markov Estimate (map 6 bits): p(max) = 1.13787e-223, min-entropy = 5.78597_**
_- Compression Estimate: p(max) = 0.00870919, min-entropy = 6.84325_
_- t-Tuple Estimate: p(max) = 0.004124, min-entropy = 7.92174_
_- LRS Estimate: p(max) = 0.00391357, min-entropy = 7.9973_

_Running predictor estimates:_
_Computing MultiMCW Prediction Estimate: 100 percent complete_
        _Pglobal: 0.003937_
        _Plocal: 0.002136_
_MultiMCW Prediction Estimate: p(max) = 0.0039373, min-entropy = 7.98858_

_Computing Lag Prediction Estimate: 100 percent complete_
        _Pglobal: 0.004073_
        _Plocal: 0.002136_
_Lag Prediction Estimate: p(max) = 0.00407281, min-entropy = 7.93976_

_Computing MultiMMC Prediction Estimate: 100 percent complete_
        _Pglobal: 0.004110_
        _Plocal: 0.002136_
_MultiMMC Prediction Estimate: p(max) = 0.00410955, min-entropy = 7.92681_

_Computing LZ78Y Prediction Estimate: 100 percent complete_
        _Pglobal: 0.004110_
        _Plocal: 0.002136_
_LZ78Y Prediction Estimate: p(max) = 0.00410961, min-entropy = 7.92678_

_min-entropy = 5.78597_

_Don't forget to run the sanity check on a restart dataset using H_I = 5.78597_

The assessed entropy for the markov test is 5.78597 bits out of 6, or 99.77%. However, when we just read that the assessed min-entropy of our data is 5.78597, we will compute that out of 8 bits, yeilding 74.82%. As a percentage, the most conservative estimate is actually the Collision Estimate, with an assessment of 6.29613 bits per byte or 78.70%

**Comment by joshuaehill** [comment]
This is the only reasonable approach when acting on un-mapped data symbols larger than 6 bits, absent substantial additional data that would allow for meaningful assessment of the full symbols. In particular, it isn't reasonable to assume that the high order bits have the same properties as the rest of the data (so simply scaling the result up to 8 bits wouldn't be reasonable).

In my experience, most situations that produce the situation noted fall into a few categories:
1. The data analyzed isn't the raw noise data, but instead some processed version of it (e.g., after going through some conditioning).
2. The data analyzed is presented to the tool in a way that obscures the underlying distribution (e.g., for a monotonic counter, sending the full counter value in rather than delta between adjacent counter values)
3. The data presented is presented to the tool in a inappropriate way (e.g., providing data with many 1-bit raw samples per input byte, providing a multi-byte noise samples to the tool -- the tool only operates on noise sources up to 8 bits wide, etc.).

We've found that many types of sources ultimately need to be mapped down to be reasonably analyzed by this tool. Some guidance on how to do this is in the 2016 draft of SP800-90B, section 6.4. This tool does not automatically do this for you, it requires that the tester manually maps the data prior to providing it to the tool.

None of this helps you if you've genuinely got a raw noise source that produces 8-bit samples; this tool will never assess such a source as producing more than 6 bits of min entropy per sample. Again, if you provided a large amount of data (enough that, say, each possible transition occurs at least 16 times), then you could sensibly remove the truncation (but this isn't consistent with the guidance of the current draft SP800-90B).

**Comment by mslpensec** [comment]
Thank you for the reply! I will revisit section 6.4 of 90B.

I agree that scaling up the result of the Markov test to 8 bits wouldn't make sense. My thought was that it might be better if the tool instead compared percentages, since these could be compared between tests on different bit sizes. This seems like a reasonable approach to me, and I would love to learn why it is not if I am mistaken.

You gave three examples of data that produces the situation I noted, but I don't understand what would happen differently if the data were properly presented to the program -- would the markov test simply result in a lower entropy percentage that is more comparable to the other tests? I don't understand how to properly compare or interpret this test result since it is out of a different bit size.

**Comment by joshuaehill** [comment]
Presenting as a percentage might be misleading, depending on how you calculate the percentage. One can't comment on the entropy contained in the top two bits; thus, the  sensible percentage result for the Markov test would still be out of the full 8 bits (not the restricted 6 bit mapped sample), thus the value in your example in the Markov test would then be 5.78597 / 8.0 (or 72% ish). It is also true that the Markov test assessed the bottom 6 bits as having 5.78597 / 6.0, but you don't know how the other tests would have assessed that truncated data without re-running the tool on the truncated data.

As an aside, I generally don't like presenting these numbers as percentages, because it leads to people assuming that everything is uniformly distributed, and this is commonly not the case. e.g., if you've assessed a byte source at 2 bits per 8 bit symbol, then all you can really say is that a full 8 bits sample contains 2 bits of min entropy, and you can't easily comment on any truncation without separately evaluating it. One can't comment on a per-bit "entropic density" unless the source is bit-oriented, or there has been some sort of conditioning that renders the entropy distribution uniform. This becomes a bigger issue when trying to chase down how non-cryptographic conditioning distributes entropy.

In the instance where you provide data that the tool can't sensibly assess, the result doesn't really mean much. Some of the examples I cited just get more complicated to deal with (e.g., multi-byte samples absolutely must be mapped down to some smaller symbol size).

One example where inputting the data properly completely resolves this issue that you cite is the instance where the raw source is really bit-oriented, and the input was inappropriately presented in 8 symbols per input byte. In this instance, you are supposed to have one bit per input byte, presented in the order they were produced by the raw source. This makes the symbol size 1 bit, and everything works without truncation. In this instance, the assessed entropy is provided on a per-bit basis, so to get the entropy of the 8 of them in a packed byte, you just multiply by 8.
