### ISSUE TITLE
RNG failing Restart Tests by NIST SP800-22

### ISSUE THREAD

**Issue by RSam1991** [usnistgov/SP800-90B_EntropyAssessment#37]
Hi, I have data sample* of 1,000,000 bytes generated by a hardware RNG. The device is certified by ENT test suite, NIST SP800-22, DIE HARDER and TestU01. I have tested my sample by [1] SP800-90B_EntropyAssessment. Minimum Entropy Estimate is 7.88237 after which I run Restart Tests. My sample fails at Restart Testing and the program displays Validation Failed, No Entropy Estimate Awarded. [2] says Randomness has three features: unpredictability, unbiasedness and non-repeatability and and the non-repeatability is validated by restart tests. I want to know if my RNG is failing Restart Tests, does it mean it offers no entropy at all?

* I have generated my data sample by connecting hardware RNG with my laptop and saved 1,000,000 bytes in a .bin file. The 1,000,000 bytes of data are generated in a single go.
[1] https://github.com/usnistgov/SP800-90B_EntropyAssessment) 
[2] Analysis and Improvement of Entropy Estimators in NIST SP 800-90B

**Comment by mslpensec** [comment]
Hello.

I have run into similar when the data for the restart test is not formatted correctly. The restart test requires a different data set than the normal test and if you try to use the same data set for both the restart test will give an error.

From 90B: 
For the restart tests (see Section 3.1.4), the entropy source must be restarted 1000 times; for each restart, 1000 consecutive samples shall be collected directly from the noise source. This data is stored in a 1000x1000 restart matrix M, where M[i][j] represents the jth sample from the ith restart.

If the restart-test tool does not get data that is in just this format, it will not run correctly.

Another possibility is that you are inputting the incorrect value for the entropy for the restart test. The value you quote in your comment looks like an output from the ent tool; the way the 90B tool is set up, if you put in 8 bit values you will never get a result greater than 6 bits of entropy per byte because of the markov test (which reduces to six bits and is thus usually the lowest value). Make sure that you are using the same entropy output that you got from the 90B tests.

If your data is collected and formatted correctly, and you are inputting the correct entropy value, then it probably means that your RNG produces correlated data when it first starts up, which doesn't necessarily mean that it has no entropy, but it does mean that it wouldn't meet the 90B standards since it is vulnerable to an attack where the attacker repeatedly turns the device off and on again, analyzes the RNG output, and finds a predictable pattern that allows them to determine the value of the RNG.

**Comment by mslpensec** [comment]
One other thought: you can try rerunning the tool with a lower entropy value, and your data may pass at a lower entropy.

**Comment by RSam1991** [comment]
@mslpensec thank you for your response. I have generated new dataset in such a way that I restart my RNG using Devcon Utility. I have generated 1000 files, each of 1000 B and have concatenated them in one file of 1,000,000 B. I have used Devcon utility to restart my device after the generation of each file (1000 B). You have mentioned that there are different files for IID_main.py and Restart.py, however the manual shows the use of same file for IID_main.py and Restart.py. Kindly guide me, if I have to generate two different test files i.e., one for iid_main.py and other for performing restart.py (for restart, my devcon file can be used, i suppose)

**Comment by RSam1991** [comment]
@mslpensec , "> One other thought: you can try rerunning the tool with a lower entropy value, and your data may pass at a lower entropy." can you kindly explain, what that lower entropy value can be? Is is some hypothetical value? Thanks

**Comment by mslpensec** [comment]
The 90B test suite comes with three different executable programs:
iid_main.py -- uses continuous data from the RNG
noniid_main.py -- uses continuous data from the RNG
restart.py -- uses "restart data" that has data from 1000 runs of the RNG.

The first two assess the entropy of your data and use one million bits of continuous output from an RNG. 
The restart test is a "sanity check" to make sure that the RNG produces uncorrelated values on startup. This should be run with a "restart" data set like the one you just made using devcon. In the example document they use the truerandom data instead of a real restart data set, and it does run, but it defeats the purpose of the restart test.

One other note: it does matter whether you run iid_main.py or noniid_main.py. iid stands for "independent and identically distributed," which is a statistical quality of data, usually only achieved through careful design of an RNG and probably through a very careful choice of the noise source. Unless you have strong reason to believe that your data is iid, it is probably not. For more on the IID assumption, see section 5 of SP800-90B: https://csrc.nist.gov/CSRC/media/Publications/sp/800-90b/draft/documents/sp800-90b_second_draft.pdf

As for the second thought, about running the restart test using different entropy values: 

The restart test assesses the entropy of each row and column of the matrix. If it finds less entropy than in the overall data set, then the data doesn't pass. When I was working with the tool I noticed that if I put in a number lower than the output of noniid_main.py, the data will still pass the restart test, but if I put in a higher entropy, the restart test will probably not pass. I am not sure about what this means (ideally, you can use the exact same number that you get from the output of noniid_main.py) but my thinking is that you would basically be lowering your assessed entropy until you reach the point where you hit the amount of entropy in each individual row and column. For more on the restart test, see SP800-90B 3.1.4.3

**Comment by RSam1991** [comment]
@mslpensec  thanks alot, I will perform the tests as per your guidance.

**Comment by joshuaehill** [comment]
The 2016 draft SP800-90B restart testing is a really very flawed construction. It's much better in the final SP800-90B version of the tests, but still has significant problems. See comment #3 in our SP800-90B comments: http://bit.ly/2jwKN9R

**Comment by joshuaehill** [comment]
See the related issue #56.

**Comment by joshuaehill** [comment]
At this point, I think that this issue can be closed.
