### ISSUE TITLE
Test result by MemoryError

### ISSUE THREAD

**Issue by Mysstouz** [usnistgov/SP800-90B_EntropyAssessment#40]
Hi guys,

I tried to execute iid_main.py and noniid_main.py with a personnal bin file, but all test finished by the message "MemoryError".

> dist@fant-pc:~/Documents/work_bin/SP800-90B_EntropyAssessment-master$ python3 iid_main.py -v ../ex_data.bin 8
reading 167772160 bytes of data
Read in file ../ex_data.bin, 167772160 bytes long.
Dataset: 167772160 8-bit symbols, 256 symbols in alphabet.
Output symbol values: min = 0, max = 255
Calculating statistics on original sequence
Traceback (most recent call last):
  File "iid_main.py", line 54, in <module>
    passed_permutation_tests = permutation_test(list(dataset), verbose)
  File "/home/dist/Documents/work_bin/SP800-90B_EntropyAssessment-master/permutation_tests.py", line 414, in permutation_test
    t['compression'] = compression(s)
  File "/home/dist/Documents/work_bin/SP800-90B_EntropyAssessment-master/permutation_tests.py", line 264, in compression
    encodeS = " ".join([str(i) for i in s])
  File "/home/dist/Documents/work_bin/SP800-90B_EntropyAssessment-master/permutation_tests.py", line 264, in <listcomp>
    encodeS = " ".join([str(i) for i in s])
MemoryError

Others have already had this problem? How was it settled ? or change the lines of the file permutation_tests.py are required.

I use Python 3 (64 bits) and Ubuntu 14.04 LTS 64 bits.

Thank you in advance

**Comment by joshuaehill** [comment]
It looks like you're running this on 167 million samples, which (for this implementation) is going to take a staggering amount of memory and time to complete. To proceed, try to trim that down to 1,000,000 samples per run. (If you want to look at all of the data, you can  perform 167 of these rounds of testing).

Also, I note that you're using 8 bit samples; please see my comments on issue #34 commenting on such situations.

**Comment by Mysstouz** [comment]
Ok, thank you for your answer. 
I will try with a more powerfull machine otherwise trim the file.

**Comment by mslpensec** [comment]
@joshuaehill I am interested in your suggestion to look at larger data sets one million samples at a time. I have noticed that the MultiMMC estimate to hangs with datafiles larger than two million samples (using 64 bit python 3 on a 16 GB machine). Since this test hanging doesn't prevent one from reading the results of the previous, less memory intensive tests, I've noticed that, very generally, assessing larger amounts of data results in higher min-entropy assessments (some assessments will be lower, some will be higher, but the overall trend seems to be higher with more data). Which does suggest a benefit to generating and analyzing large datasets.

If one were to proceed as you suggest, analyzing one million samples at a time to keep things manageable for the tool, would there be a sensible way to combine all of the results to get an estimate for the multi-million dataset as a whole?

Also the fact that the MultiMMC estimate in particular is where the assessment stalls out every time does make me wonder if that test could be improved, or at least gain some error handling to fail gracefully.

**Comment by kerrymckay** [comment]
I just wanted to chime in before people get too in the weeds with the way MultiMMC eats up memory. The NIST team agreed that it needs improvement from the way it was described in the second draft. MultiMMC has been updated in the final version of the document (coming out soon) and will limit the number of counters so that MultiMMC will no longer eat your computer.

**Comment by joshuaehill** [comment]
We routinely look at large data sets this way; we're often looking for distinct "modes" of the entropy source, so we take a low percentile of the resulting assessments. We also do testing on the full set of data in these cases (sans MultiMMC test), but that may be difficult to accomplish in a reasonably period of time with the reference implementation.

Any implementation of the current specification of the MultiMMC test requires a substantial amount of memory for large data sets made up of many symbols. Fundamentally, with k symbols, the storage is dominated by k-strings of length 16; one bound of the memory consumption is O(k^16), and another is proportional to the total number of 16-symbol strings in your data set. For this second bound, you either use a magical hash table (which will have all sorts of hidden terms dependent on its construction), or you end up with a k term in the product (as one way to conceptualize this task is building a k-way tree). So, you get O(n) storage for (in practice, slow) magical hash table implementations, and O(kn) storage for tree implementations.

**Comment by joshuaehill** [comment]
One interesting aside: the O(k^16) bound (correctly) suggests that the MultiMMC can be made to be quite efficient for binary data; you can efficiently test basically any amount of binary data using this test.
