### ISSUE TITLE
Using more than 8 bit per sample

### ISSUE THREAD

**Issue by kroeckx** [usnistgov/SP800-90B_EntropyAssessment#8]
I'm in the process of evaluating a source of entropy and found this.

It's using a 12 bit ADC and if I calculate the min entropy myself I get 8.22.  It's a bell shaped distribution.

But if I try to use noniid_main.py, I get the error message "assert bits_per_symbol <= 8".

Is this something you plan on fixing?

I was also reading the draft it links too, and I'm a bit confused why it seems to be limiting the sample space to 256 and currently fail see why.

**Comment by kerrymckay** [comment]
The code currently restricts the symbol size to 8 bits to enforce the sample size limit. Any conversions you wish to make must be done before you can apply noniid_main.py. The assertion (or similar mechanism) will remain in the code as long as the sample size limit is in the guidance.

The restricted sample space comes about because we have to specify how much data to collect, and if the sample space is too large, then there will not be enough data to make a meaningful estimate. Also, larger sample spaces cause the Markov-based estimators to require too much memory. For this version of the guidance, there is no plan to remove the sample space restriction.

**Comment by kroeckx** [comment]
I was confused for a while about your comment.  What I think you''re trying to say is that if there is a 32-bit (4G) sample space, taking only 1M samples isn't going to give good results.  With the current draft you need to take at least around 4000 more samples than your sample space.

Anyway, in section 6.4 it talks how to reduce the sample spaces, and so it seems you then need to select the 8 bits that have the most entropy, and so would end up under estimating your entropy.  But there doesn't seem to be a tool to actually do that.

I would also actually prefer to have a good estimate of it instead, and so I undid commit 14b05fdb2de2c68c74f688196a227654b00c1d69 and 062cbec1ee68b7045bce8826befb4e13de2fe684 and it just works.
