### ISSUE TITLE
Query on LRS estimate results

### ISSUE THREAD

**Issue by msp79** [usnistgov/SP800-90B_EntropyAssessment#9]
Hi,

I am running non IID tests and below are the results.

As you can notice in the below results,  all the results look fine except LRS estimate. Is this value acceptable ? If no, could you please let me know what could be wrong with the data provided ? Any suggestions on how I can improve the LRS result ?

non IID results:
Running entropic statistic estimates:
- Most Common Value Estimate: p(max) = 0.00422482, min-entropy = 7.88689
- Collision Estimate: p(max) = 0.0109435, min-entropy = 6.51379
- Markov Estimate (map 6 bits): p(max) = 1.29061e-223, min-entropy = 5.78455
- Compression Estimate: p(max) = 0.00773644, min-entropy = 7.01411
- t-Tuple Estimate: p(max) = 0.00591608, min-entropy = 7.40114
- LRS Estimate: p(max) = 0.185701, min-entropy = 2.42894

Running predictor estimates:
Computing MultiMCW Prediction Estimate: 100 percent complete
        Pglobal: 0.003989
        Plocal: 0.002136
MultiMCW Prediction Estimate: p(max) = 0.00398937, min-entropy = 7.96962

Computing Lag Prediction Estimate: 100 percent complete
        Pglobal: 0.004115
        Plocal: 0.002136
Lag Prediction Estimate: p(max) = 0.00411464, min-entropy = 7.92502

Computing MultiMMC Prediction Estimate: 100 percent complete
        Pglobal: 0.004072
        Plocal: 0.002136
MultiMMC Prediction Estimate: p(max) = 0.00407179, min-entropy = 7.94012

Computing LZ78Y Prediction Estimate: 100 percent complete
        Pglobal: 0.004072
        Plocal: 0.002136
## LZ78Y Prediction Estimate: p(max) = 0.00407185, min-entropy = 7.9401

min-entropy = 2.42894

Don't forget to run the sanity check on a restart dataset using H_I = 2.42894

Thanks
Mahendra

**Comment by kerrymckay** [comment]
There are three places where something could be bad: 1) the estimator design, 2) this implementation, and 3) your data. 

I have had a similar discussion with someone over email. In their case, there turned out to be a bug in their source causing a long sequence of symbols that was repeated. You will have to look at your data to determine if a long repeated sequence is causing this issue.  Try running the LRS estimate with its verbose flag set to True to get more information (this is not done by noniid_main.py, even when it is in verbose mode)
